import '../../features/user/domain/entities/learning_dashboard.dart';

abstract final class LearningCatalogSeed {
  static const topics = <LearningTopic>[
    LearningTopic(
      topicId: 'logic',
      name: 'Logica de programacao',
      description: 'Fundamentos para decompor problemas e criar algoritmos.',
      parentTopicId: null,
      prerequisiteTopicIds: <String>[],
      contentTypes: <LearningContentType>[
        LearningContentType.theory,
        LearningContentType.exercise,
      ],
      difficulty: TopicDifficulty.easy,
      order: 10,
      totalExercises: 1,
      xpReward: 40,
      coinReward: 8,
      isActive: true,
    ),
    LearningTopic(
      topicId: 'variables',
      name: 'Variaveis e tipos',
      description: 'Armazenamento, conversao e uso de dados em programas.',
      parentTopicId: null,
      prerequisiteTopicIds: <String>[],
      contentTypes: <LearningContentType>[
        LearningContentType.theory,
        LearningContentType.exercise,
        LearningContentType.quiz,
      ],
      difficulty: TopicDifficulty.easy,
      order: 20,
      totalExercises: 2,
      xpReward: 60,
      coinReward: 12,
      isActive: true,
    ),
    LearningTopic(
      topicId: 'input-output',
      name: 'Entrada e saida',
      description: 'Leitura de entradas e exibicao de resultados claros.',
      parentTopicId: null,
      prerequisiteTopicIds: <String>[],
      contentTypes: <LearningContentType>[LearningContentType.theory],
      difficulty: TopicDifficulty.easy,
      order: 30,
      totalExercises: 1,
      xpReward: 30,
      coinReward: 6,
      isActive: true,
    ),
    LearningTopic(
      topicId: 'conditions',
      name: 'Condicionais',
      description: 'Decisoes com comparadores, if, elif e else.',
      parentTopicId: null,
      prerequisiteTopicIds: <String>[],
      contentTypes: <LearningContentType>[
        LearningContentType.theory,
        LearningContentType.exercise,
        LearningContentType.quiz,
      ],
      difficulty: TopicDifficulty.medium,
      order: 40,
      totalExercises: 2,
      xpReward: 80,
      coinReward: 16,
      isActive: true,
    ),
    LearningTopic(
      topicId: 'loops',
      name: 'Lacos de repeticao',
      description: 'Repeticoes, acumuladores e percursos em listas.',
      parentTopicId: null,
      prerequisiteTopicIds: <String>[],
      contentTypes: <LearningContentType>[
        LearningContentType.theory,
        LearningContentType.exercise,
        LearningContentType.quiz,
      ],
      difficulty: TopicDifficulty.medium,
      order: 50,
      totalExercises: 2,
      xpReward: 90,
      coinReward: 18,
      isActive: true,
    ),
    LearningTopic(
      topicId: 'functions',
      name: 'Funcoes',
      description: 'Regras reutilizaveis com parametros e retorno.',
      parentTopicId: null,
      prerequisiteTopicIds: <String>[],
      contentTypes: <LearningContentType>[
        LearningContentType.theory,
        LearningContentType.challenge,
      ],
      difficulty: TopicDifficulty.hard,
      order: 60,
      totalExercises: 1,
      xpReward: 100,
      coinReward: 20,
      isActive: true,
    ),
  ];

  static String? topicIdForActivity(String activityId) {
    return switch (activityId) {
      'hello-world' => 'logic',
      'sum' => 'variables',
      'approval' => 'conditions',
      'streak' => 'loops',
      'mastery-function' => 'functions',
      _ => null,
    };
  }
}
