// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCddk2fT6TneE-yrY58v9o2I76fu0KBBkI',
    appId: '1:798060061562:web:9b29aba066bccdb3f5acc3',
    messagingSenderId: '798060061562',
    projectId: 'protech-uespi-sergio',
    authDomain: 'protech-uespi-sergio.firebaseapp.com',
    storageBucket: 'protech-uespi-sergio.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxz1zwsqToaEtNIG3fFi1ZoBJBbcePWrI',
    appId: '1:798060061562:android:a2f2ef6e5ff3c5cdf5acc3',
    messagingSenderId: '798060061562',
    projectId: 'protech-uespi-sergio',
    storageBucket: 'protech-uespi-sergio.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXkpmzfU9vZ_LwoEDC_ONS51sOCC12c1M',
    appId: '1:798060061562:ios:78026d2c706ba09bf5acc3',
    messagingSenderId: '798060061562',
    projectId: 'protech-uespi-sergio',
    storageBucket: 'protech-uespi-sergio.firebasestorage.app',
    iosBundleId: 'com.example.protechctu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXkpmzfU9vZ_LwoEDC_ONS51sOCC12c1M',
    appId: '1:798060061562:ios:78026d2c706ba09bf5acc3',
    messagingSenderId: '798060061562',
    projectId: 'protech-uespi-sergio',
    storageBucket: 'protech-uespi-sergio.firebasestorage.app',
    iosBundleId: 'com.example.protechctu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCddk2fT6TneE-yrY58v9o2I76fu0KBBkI',
    appId: '1:798060061562:web:65b2bd0049d85856f5acc3',
    messagingSenderId: '798060061562',
    projectId: 'protech-uespi-sergio',
    authDomain: 'protech-uespi-sergio.firebaseapp.com',
    storageBucket: 'protech-uespi-sergio.firebasestorage.app',
  );
}
